-- Καθαρίζει όλους τους v2 πίνακες πριν το v3 schema.
-- Ασφαλές γιατί έχουμε μόνο test data στη v2.
DROP TABLE IF EXISTS
  case_documents,
  finance_exoda_exoterikou_synergati,
  finance_amoives_dikigoron,
  finance_pagia_exoda_case,
  finance_ores,
  finance_case, finance_exoda_pagia, finance_exoda_exoterika, finance_amoives,
  dikastiria_dikigoroi,
  dikastiria_energeies_exelixeis,
  dikastiria_energeies,
  energeies,
  sxetikes_ypotheseis,
  xeiristes_dikigoroi,
  ypotheseis,
  antidikoi,
  dikigoroi_antidikon,
  dikigoroi_grafeiou,
  sxetika_prosopa,
  nomika_prosopa,
  fysika_prosopa,
  dikastiria_exelixi_energeias,
  dikastiria_grammateis,
  dikastiria_dikastes,
  dikastiria_tmimata,
  dikastiria,
  amoives,
  pagia_exoda,
  eidos_sxesis,
  theseis_arxeiothetisis,
  ypotheseis_onomasies,
  thesi,
  diadikasies,
  phone_types,
  address_type,
  cities,
  countries,
  stoixeia_epixeirisis,
  documents, cases, persons, courts,           -- πιθανά v2 names
  users, organizations
CASCADE;
